spring.application.name=peque_backend
spring.datasource.url=jdbc:mysql://localhost:3306/db_ventas
spring.datasource.username=root
spring.datasource.password=database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gdani4l981@gmail.com
spring.mail.password=rmrl ppib qukf watl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080
app.frontend-url=http://localhost:4200
app.qr.base-url=

niubiz.user=integraciones@niubiz.com.pe
niubiz.password=_7z3@8fF
niubiz.merchant-id=456879852
niubiz.base-url=https://apisandbox.vnforappstest.com
niubiz.yape-auth-channel=yape
niubiz.yape-token-url=https://apisandbox.vnforappstest.com/api.ecommerce/v2/ecommerce/token/yape/

gemini.api-key=AQ.Ab8RN6K9j_ruTMEz5woZaSrW8O7J-w67SouOGBI4goeQGjKCiw
gemini.model=gemini-2.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta

app.jwt.secret=onjpOPFjfjpJPFDDKOPADADMPApm456dadadaDADDDADDADASDADQFQF
app.jwt.expiration-hours=8
